name: Test

on: [push, pull_request]

jobs:
  build-and-test:
    name: 'Build on ${{ matrix.platform }} with node.js ${{ matrix.node-version }}'
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [12]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: yarn

      - name: Test
        run: yarn test
